services:
  - type: web
    name: indian-market-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python market_monitor_render.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
