name: Stock Market Monitor

on:
  schedule:
    # Run every 15 minutes during trading hours (IST)
    # 9:15 AM to 3:30 PM IST = 3:45 AM to 10:00 AM UTC
    - cron: '15,30,45 4-9 * * 1-5'  # Every 15 min, 4-9 AM UTC, Mon-Fri
    - cron: '0 5-9 * * 1-5'         # Every hour, 5-9 AM UTC, Mon-Fri
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run stock analysis
      run: python sunpharma_monitor_production.py
      
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: stock-monitor-logs
        path: stock_monitor.log
